styles:
    - name: "box-nobrand"
      image: "general.png"
      title: "New Part"
      x: 137
      y: 180
      imageWidth: 900
      imageHeight: 540
      labelWidth: 240
      labelHeight: 95
      titleFontSize: 19
      oemFontSize: 25
    - ad:
      name: "ad"
      image: "general.png"
      title: "New Part"
      x: 100
      y: 100
redis:
    host: redis
    port: 6379
    db: 0
    pass: